<a href="https://colab.research.google.com/github/amanosan/Pytorch-Tutorials/blob/master/PyTorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import torch

In [ ]:
print(torch.__version__)

1.7.1+cu101


### Initializing Tensors

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device) 

In [ ]:
print(f"{tensor1}, {tensor1.device}, {tensor1.dtype}, {tensor1.shape}")

tensor([[1., 2., 3.],
        [4., 5., 6.]]), cpu, torch.float32, torch.Size([2, 3])


In [ ]:
# junk values with specified shape
tensor2 = torch.empty(size=(3,3))
print(tensor2)

tensor([[3.4714e-32, 3.0914e-41, 3.3631e-44],
        [0.0000e+00,        nan, 1.4013e-45],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


In [ ]:
# tensor with zeros
tensor3 = torch.zeros(size=(3,3))
print(tensor3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# random value initialization
tensor4 = torch.rand(size=(3,3))
print(tensor4)

tensor([[0.6007, 0.3759, 0.5007],
        [0.7023, 0.3512, 0.2250],
        [0.3424, 0.4061, 0.9846]])


In [ ]:
# tensor one initialization
tensor5 = torch.ones(size=(3,3))
print(tensor5) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# tensor with identity initialization
tensor6 = torch.eye(3, 3)
print(tensor6)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# tensor arange function
tensor7 = torch.arange(start=0, end=5, step=1)
print(tensor7)

tensor([0, 1, 2, 3, 4])


In [ ]:
# tensor linspace function
tensor8 = torch.linspace(start=0.1, end=1, steps=10)
print(tensor8)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [ ]:
# tensor with specified mean and std normal distribution
tensor9 = torch.rand(size=(3,3)).normal_(mean=0, std=1)
print(tensor9)

tensor([[ 0.2959,  1.9589,  1.2967],
        [ 0.4268, -0.1759,  0.4871],
        [ 0.9903,  0.9670,  0.3603]])


In [ ]:
# tensor with uniform distribution
tensor = torch.rand(size=(3,3)).uniform_(0, 10) # (start, end)
print(tensor)

tensor([[2.9606, 2.2650, 0.8438],
        [6.6940, 1.9715, 4.3702],
        [6.0936, 4.3069, 8.5076]])


In [ ]:
# Converting Tensors to different data types
tensor = torch.arange(4)
print(tensor, tensor.dtype)
print(tensor.bool(), tensor.bool().dtype)  # convert to boolean
print(tensor.short(), tensor.short().dtype)  # convert to int16
print(tensor.long(), tensor.long().dtype)  # convert to int64 (default value)
print(tensor.half(), tensor.half().dtype)  # convert to float16
print(tensor.float(), tensor.float().dtype)  # convert to float32
print(tensor.double(), tensor.double().dtype)  # convert to float64

tensor([0, 1, 2, 3]) torch.int64
tensor([False,  True,  True,  True]) torch.bool
tensor([0, 1, 2, 3], dtype=torch.int16) torch.int16
tensor([0, 1, 2, 3]) torch.int64
tensor([0., 1., 2., 3.], dtype=torch.float16) torch.float16
tensor([0., 1., 2., 3.]) torch.float32
tensor([0., 1., 2., 3.], dtype=torch.float64) torch.float64


In [ ]:
# ARRAY TO TENSOR CONVERSION AND VICE-VERSA

In [ ]:
import numpy as np

In [ ]:
a_array = np.random.random((5,5))
a_tensor = torch.from_numpy(a_array) # from array to tensor 

In [ ]:
print(a_array)
print(a_tensor)

[[0.58580273 0.04506678 0.97193264 0.57003978 0.41124155]
 [0.91465461 0.27863151 0.72221944 0.01069075 0.52466453]
 [0.70189438 0.9891969  0.42246233 0.54402372 0.51642545]
 [0.87129862 0.3693617  0.30067424 0.10282073 0.0805993 ]
 [0.46460124 0.45954868 0.01861135 0.14731194 0.27393291]]
tensor([[0.5858, 0.0451, 0.9719, 0.5700, 0.4112],
        [0.9147, 0.2786, 0.7222, 0.0107, 0.5247],
        [0.7019, 0.9892, 0.4225, 0.5440, 0.5164],
        [0.8713, 0.3694, 0.3007, 0.1028, 0.0806],
        [0.4646, 0.4595, 0.0186, 0.1473, 0.2739]], dtype=torch.float64)


In [ ]:
b_array = a_tensor.numpy()  # from tensor back to numpy array
print(type(b_array))
print(b_array)

<class 'numpy.ndarray'>
[[0.58580273 0.04506678 0.97193264 0.57003978 0.41124155]
 [0.91465461 0.27863151 0.72221944 0.01069075 0.52466453]
 [0.70189438 0.9891969  0.42246233 0.54402372 0.51642545]
 [0.87129862 0.3693617  0.30067424 0.10282073 0.0805993 ]
 [0.46460124 0.45954868 0.01861135 0.14731194 0.27393291]]


### Tensor Math and Comparison Operations

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([7, 8, 9])

In [ ]:
# addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)

z2 = torch.add(x, y)

z = x + y

print(z1)
print(z2)
print(z)

tensor([ 8., 10., 12.])
tensor([ 8, 10, 12])
tensor([ 8, 10, 12])


In [ ]:
# subtraction
z = x - y
print(z)

tensor([-6, -6, -6])


In [ ]:
# division
z = torch.true_divide(y, x)  # element wise division if both tensors are of equal shape
print(z)

tensor([7., 4., 3.])


In [ ]:
# multiplication
z = x * y
print(z)

tensor([ 7, 16, 27])


In [ ]:
# INPLACE operations
t = torch.zeros(3)
t.add_(x) # underscore (_) after the function indicates inplace operation, similar to 't += x'
print(t)

tensor([1., 2., 3.])


In [ ]:
# Exponentiation
z1 = x.pow(2)
print(z1)
z2 = x ** 2
print(z2)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [ ]:
# Simple Comparisons

z1 = x >= 2
print(z1)

tensor([False,  True,  True])


In [ ]:
# Matrix Multiplications

x1 = torch.rand(size=(2, 5))
x2 = torch.rand(size=(5, 3))

x3 = torch.mm(x1, x2)
print(x3)

x4 = x1.mm(x2)
print(x4)
# both the above ways are same way of doing matrix multiplication

tensor([[0.9598, 1.6832, 1.4374],
        [0.6225, 1.1631, 1.3443]])
tensor([[0.9598, 1.6832, 1.4374],
        [0.6225, 1.1631, 1.3443]])


In [ ]:
# Matrix Exponentiation
matrix_exp = torch.rand((5, 5))

print(matrix_exp.matrix_power(3))  # multiplying the matrix three times with itself (m1.m1.m1)

tensor([[2.6660, 1.7459, 2.7926, 3.6825, 1.8423],
        [1.2836, 1.1360, 1.1803, 1.6939, 0.9909],
        [2.0700, 1.6391, 2.0489, 2.7830, 1.4680],
        [2.1408, 1.5757, 2.1822, 2.8812, 1.5482],
        [2.1361, 1.5401, 2.1962, 2.9294, 1.4522]])


In [ ]:
# Dot Product
z = torch.dot(x, y)
print(z)

tensor(50)


In [ ]:
# Batch matrix multiplication
batch = 32
m = 10
n = 20
p = 30

tensor1 = torch.rand((batch, m ,n))
tensor2 = torch.rand((batch, n, p))

z = torch.bmm(tensor1, tensor2)
print(z.shape)

torch.Size([32, 10, 30])


In [ ]:
# OTHER USEFUL TENSOR OPERATIONS

t = torch.rand(size=(2, 2)) * 10

print(t)

tensor([[0.0276, 1.1016],
        [0.6195, 0.9884]])


In [ ]:
print(torch.sum(t, dim=0))  # prints the sum of tensor column wise
print(torch.sum(t, dim=1))  # prints the sum row wise

tensor([0.6470, 2.0901])
tensor([1.1292, 1.6079])


In [ ]:
# maximum value
values, indeces = torch.max(t, dim=0)
print(values, indeces)

tensor([0.6195, 1.1016]) tensor([1, 0])


In [ ]:
# minimum value
values, indeces = torch.min(t, dim=1)
print(values, indeces)

tensor([0.0276, 0.6195]) tensor([0, 0])


In [ ]:
# index of the maximum values
ids = torch.argmax(t, dim=0)
print(ids)

tensor([1, 0])


In [ ]:
# finding the mean
mean_t = torch.mean(t.float(), dim=0)
print(mean_t)

tensor([0.3235, 1.0450])


In [ ]:
# element wise equality
t1 = torch.tensor([1, 2, 3, 4, 5])
t2 = torch.tensor([1, 6, 4, 4, 5])

z = torch.eq(t1, t2)
print(z)

tensor([ True, False, False,  True,  True])


In [ ]:
# sorting tensors

sorted_tensor, sorted_idx = torch.sort(t, dim=1, descending=False)
print(sorted_tensor)
print(sorted_idx)

tensor([[0.0276, 1.1016],
        [0.6195, 0.9884]])
tensor([[0, 1],
        [0, 1]])


In [ ]:
# clamping tensor 
t1 = torch.tensor([102, 14, 15, 16, -15, 65, 234])
z = torch.clamp(t1, min=0, max=100)
# clamps down max value to 100 and min to 0
print(z)

tensor([100,  14,  15,  16,   0,  65, 100])


In [ ]:
# looking for true values
t1 = torch.tensor([1, 1, 1, 0, 1, 0], dtype=torch.bool)

z1 = torch.any(t1)  # returns true if any one of the value is true
z2 = torch.all(t1)  # returns true if all the values in tensor are true

print(z1)
print(z2)

tensor(True)
tensor(False)


### Tensor Indexing

In [ ]:
batch = 10
features = 25
t = torch.rand((batch, features))

In [ ]:
# getting all features of first sample
print(t[0].shape)  # we will get all the 25 features

torch.Size([25])


In [ ]:
# getting first features of all the samples
print(t[:, 0])

tensor([0.0491, 0.6124, 0.7058, 0.5425, 0.5900, 0.0986, 0.1746, 0.3089, 0.2362,
        0.0689])


In [ ]:
# getting first 10 features of 3rd sample
print(t[2, :10])

tensor([0.7058, 0.8835, 0.9970, 0.3324, 0.3977, 0.3618, 0.6471, 0.9012, 0.6400,
        0.2811])


In [ ]:
# getting particular index values
t1 = torch.rand(10) * 100
t2 = torch.rand((3, 5)) * 100
idx = [2, 5, 8]
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

print(t1)
print(t1[idx])
print("******************")
print(t2)
print(t2[rows, cols])

tensor([17.1009, 20.2742, 57.9833, 54.5560, 26.1271,  7.8246, 14.1212, 19.8662,
         4.8264, 33.8358])
tensor([57.9833,  7.8246,  4.8264])
******************
tensor([[22.3223, 83.3874,  5.9317, 21.3346, 11.0454],
        [96.2399, 94.5868, 42.5045, 43.7847, 54.6751],
        [59.7881, 98.7516, 15.5193,  3.1875, 81.6057]])
tensor([54.6751, 22.3223])


In [ ]:
# getting values with constraints
t1 = torch.arange(10)
print(t1[(t1 > 2) & (t1 < 8)])
print(t1[(t1.remainder(2) == 0) & (t1 > 0)])  # prints even numbers in the tensor

tensor([3, 4, 5, 6, 7])
tensor([2, 4, 6, 8])


In [ ]:
# more useful operations
t1 = torch.arange(10)
print(torch.where((t1 < 5), t1, t1 * 2))
print(torch.tensor([1,2,3,1,2,3,1,2,3,1,2,3,3,3,3,4]).unique())  # returns the number of unique elements 
print(torch.rand((3, 5)).ndimension())  # returns the dimension
print(torch.rand((3, 5)).numel())  # returns the number of elements

tensor([ 0,  1,  2,  3,  4, 10, 12, 14, 16, 18])
tensor([1, 2, 3, 4])
2
15


### Tensor Reshaping Dimensions

In [ ]:
# reshaping
x = torch.arange(9)

x1 = x.view(3, 3)
x2 = x.reshape(3, 3)

print(x1.shape, x2.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [ ]:
x = torch.arange(9).reshape(3, 3)

print(x)
print(x.t())  # transpose of the tensor

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [ ]:
# concatinating tensors
x1 = torch.rand(2, 5) * 100
x2 = torch.rand(2, 5)

print(torch.cat((x1, x2), dim=0))

tensor([[31.9986, 85.1664, 99.2996, 15.8005, 80.5787],
        [52.2094, 82.9925, 74.5029, 86.1993, 25.9206],
        [ 0.5027,  0.4175,  0.8244,  0.1777,  0.1422],
        [ 0.8414,  0.3196,  0.8999,  0.6435,  0.9972]])


In [ ]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.reshape(batch, -1)
y = x.permute(0, 2, 1)
print(x.shape)
print(z.shape)
print(y.shape)
print(x.permute(2, 0, 1).shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])
torch.Size([64, 5, 2])
torch.Size([5, 64, 2])


In [ ]:
# adding a dimension
x = torch.arange(10)  # shape - [10]
y = x.unsqueeze(0)  # shape - [1,10]
z = x.unsqueeze(1)  # shape - [10,1]

print(x.shape)
print(y.shape)
print(z.shape)

# to remove the dimension use squeeze method
x1 = z.squeeze(1)
x2 = y.squeeze(0) 
print(x1.shape)
print(x2.shape)

torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([10])
torch.Size([10])


### Creating a fully connected Neural Network

In [ ]:
# imports
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import torch.nn.functional as F
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [ ]:
# Creating fully connected network
class NN(nn.Module):
  def __init__(self, input_size, num_classes):
    super(NN, self).__init__()
    self.fc1 = nn.Linear(input_size, 50)
    self.fc2 = nn.Linear(50, num_classes)

  # forward propogation
  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return x

In [ ]:
# Setting up device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
# Hyperparameters
input_size=784
num_classes=10
lr = 0.001
batch_size=64
epochs=1

In [ ]:
# loading the data
train_mnist = datasets.MNIST(root='mnist/', train=True, transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(dataset=train_mnist, batch_size=batch_size, shuffle=True)

test_mnist = datasets.MNIST(root='mnist/', train=False, transform=transforms.ToTensor(), download=True)
test_loader = DataLoader(dataset=test_mnist, batch_size=batch_size, shuffle=False)

In [ ]:
# Initializing the model
model = NN(input_size=input_size, num_classes=num_classes).to(device)

In [ ]:
# Loss and Optimizers
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=lr)

In [ ]:
# Training the Network
for epoch in range(epochs):
  for batch_idx, (data, targets) in enumerate(train_loader):
    data = data.to(device=device)
    targets = targets.to(device=device)

    # reshaping the data to give to neural network
    data = data.reshape(data.shape[0], -1)

    # forward propagation
    scores = model(data)
    loss = criterion(scores, targets)

    # backward propagation
    optimizer.zero_grad()
    loss.backward()

    # gradient descent 
    optimizer.step()

In [ ]:
# Checking accuracy on training and test 
def check_accuracy(loader, model):
  num_correct = 0
  num_samples = 0
  model.eval()

  with torch.no_grad():
    for x, y in loader:
      x = x.to(device=device)
      y = y.to(device=device)

      x = x.reshape(x.shape[0], -1)
      scores = model(x)

      _, predictions = scores.max(1)

      num_correct += (predictions == y).sum()
      num_samples += predictions.size(0)

    acc = float(num_correct/num_samples) * 100
    print(f"Got {num_correct}/{num_samples} with accuracy {acc:.2f}")


In [ ]:
# Checking accuracy
check_accuracy(train_loader, model)
check_accuracy(test_loader, model)

Got 55764/60000 with accuracy 92.94
Got 9287/10000 with accuracy 92.87


### Convolutional Neural Network with PyTorch

In [ ]:
# Imports
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision.transforms as transforms
import torchvision.datasets as datasets

In [ ]:
# Creating the CNN class
class CNN(nn.Module):
  def __init__(self, in_channels=1, num_classes=10):
    super(CNN, self).__init__()
    self.conv1 = nn.Conv2d(in_channels=1, out_channels=8, kernel_size=(3,3), stride=(1,1), padding=(1,1))
    self.pool = nn.MaxPool2d(kernel_size=(2,2), stride=(2,2))
    self.conv2 = nn.Conv2d(in_channels=8, out_channels=16, kernel_size=(3,3), padding=(1,1), stride=(1,1))
    self.fc1 = nn.Linear(16 * 7 * 7, out_features=num_classes)

  def forward(self, x):
    x = F.relu(self.conv1(x))
    x = self.pool(x)
    x = F.relu(self.conv2(x))
    x = self.pool(x)
    x = x.reshape(x.shape[0], -1)
    x = self.fc1(x)
    return x
    

In [ ]:
# Setting up the device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
# Hyperparameters
in_channels = 1
num_classes = 10
batch_size = 64
epochs = 5
learning_rate = 0.001

In [ ]:
# Initializing the model
model = CNN(in_channels=in_channels, num_classes=num_classes).to(device)

In [ ]:
# Optimizers and Loss functions
optimizer = optim.Adam(params=model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

In [ ]:
for epoch in range(epochs):
  for batch_idx, (data, target):
    data = data.to(device=device)
    target=  target.to(device=device)

    # reshaping the data
    data = data.reshape(data.shape[0], -1)

    # forward
    scores = model(data)
    loss = criterion(scores, target)

    # backpropagation
    optimizer.zero_grad()
    loss.backward()

    # gradient step / adam step
    optimizer.step()

In [ ]:
check_accuracy(train_loader, model)
check_accuracy(test_loader, model)

### Recurrent Neural Networks with Pytorch

In [ ]:
# creating an RNN

In [ ]:
# Imports
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision.transforms as transforms
import torchvision.datasets as datasets

In [ ]:
# Hyperparameters
input_size=28
sequence_len=28
num_classes=10
learning_rate=0.001
epochs=2
batch_size=64
hidden_size=256
num_layers=2

In [ ]:
# Creating the model
class RNN(nn.Module):
  def __init__(self, input_size, hidden_size, num_layers, num_classes):
    super(RNN, self).__init__()
    self.hidden_size=hidden_size
    self.num_layers = num_layers

    self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
    self.fc = nn.Linear(hidden_size*sequence_len, num_classes)

  def forward(self, x):
    # hidden state init
    h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

    # forward propagation
    out, _ = self.rnn(x, h0)
    out = out.reshape(out.shape[0], -1)
    out = self.fc(out)
    return out

In [ ]:
# Hyperparameters
input_size=28
sequence_len=28
num_classes=10
learning_rate=0.001
epochs=2
batch_size=64
hidden_size=256
num_layers=2

In [ ]:
# Bidirectional LSTM
class BRNN(nn.Module):
  def __init__(self, input_size, hidden_size, num_layers, num_classes):
    super(BRNN, self).__init__()
    self.hidden_size = hidden_size
    self.num_layers = num_layers
    
    self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=True)
    self.fc = nn.Linear(hidden_size*2, num_classes)

  def forward(self):
    h0 = torch.zeros(self.num_layers*2, x.size(0), self.hidden_size).to(device)
    c0 = torch.zeros(self.num_layers*2, x.size(0), self.hidden_size).to(device)

    out, _ = self.lstm(x, (h0, c0))
    out = self.fc(out[:, -1, :])
    return out

In [ ]:
# initializing the model, optimizer and loss function
model = BRNN(input_size, hidden_size, num_layers, num_classes).to(device)

optim = optim.Adam(params=model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

In [ ]:
# functions to save and load model
def save_checkpoint(state, filename="my_checkpoint.pth.tar"):
  print("Saving state of the model")
  torch.save(state, filename)


def load_checkpoint(checkpoint):
  print("Loading state of the model")
  model.load_state_dict(checkpoint['state_dict'])
  optimizer.load_state_dict(checkpoint['optimizer'])

In [ ]:
# loading the model
load_model = False
if load_model:
  load_checkpoint(torch.load('my_checkpoint.pth.tar'))

In [ ]:
for epoch in range(epochs):
  losses = []

  if epoch == 2:
    checkpoint = {'state_dict': model.state_dict(), 'optimizer': optim.state_dict()}
    save_checkpoint(checkpoint)

  # saving the model dictionary at every 3rd epoch
  if epoch % 3 == 0:
    checkpoint = {'state_dict': model.state_dict()}
    save_checkpoint(checkpoint)
    
  for batch_index, (data, target) in enumerate(train_loader):
    data = data.to(device)
    target = target.to(device)

    # reshaping the data
    data = data.reshape(data.shape[0], -1)

    # forward prop
    scores = model(data)
    loss = criterion(scores, target)

    # backward prop
    optim.zero_grad()
    loss.backwards()

    optim.step()

### Transfer Learning and Fine Tuning a Model

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torchvision
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
# hyperparameters

in_channels=3
num_classes=10
learning_rate=1e-3
batch_size=1024
epochs=5

In [ ]:
# loading pretrained model
model = torchvision.models.vgg16(pretrained=True)
print(model)
# we will remove the Average Pooling and Change the classifier to output 10 classes

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [ ]:
# one way to remove the Average Pooling is to replace it with something that just forwards the data without doing anything, ie Identity Class
class Identity(nn.Module):
  def __init__(self):
    super(Identity, self).__init__()

  # the forward method just returns x without doing anything
  def forward(self, x):
    return x

In [ ]:
# lets use the Identity Class and replace Average Pooling with it
model.avgpool = Identity()
model.classifier = nn.Linear(512, 10)  # getting 10 outputs from the classifier
model.to(device)
print(model)
# as we see now, the classifier outputs 10 values and there is no Average Pooling

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [ ]:
# getting the data
train_dataset = datasets.CIFAR10(root='dataset', train=True, transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

Files already downloaded and verified


In [ ]:
# loss and optimizer 

optimizer = optim.Adam(params=model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

In [ ]:
# training the model

for epoch in range(epochs):
  losses = []
  for index, (data, target) in enumerate(train_loader):

    data = data.to(device)
    target = target.to(device)

    # forward prop
    scores = model(data)
    loss = criterion(scores, target)
    losses.append(loss.item())
    # backward prop
    optimizer.zero_grad()
    loss.backward()

    # gradient step
    optimizer.step()
  print(f"Cost at Epoch {epoch + 1}: {(sum(losses)/len(losses))}")

Cost at Epoch 1: 2.1953284472835306
Cost at Epoch 2: 1.5895737336606395
Cost at Epoch 3: 1.1356552170247447
Cost at Epoch 4: 0.7795456392424447
Cost at Epoch 5: 0.5317610289369311


In [ ]:
# Above we backpropagated through the entire model, whereas we only require or need to change the weights of only a few layers
# we set the property 'requires_grad' to False in model parameters

In [ ]:
# for params in model.parameters():
#   params.requires_grad = False

# The above code will not train any layer as we have set all the layers to False

In [ ]:
import torch 
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import torchvision.datasets as datasets
from torch.utils.data import DataLoader

In [ ]:
# setting the device 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
# hyperparameters

in_channels=3
num_classes=10
learning_rate=1e-3
batch_size=1024
epochs=5

In [ ]:
# getting the data
train_data = datasets.CIFAR10(root='dataset/', train=True, transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)


Extracting dataset/cifar-10-python.tar.gz to dataset/


In [ ]:
class Identity(nn.Module):
  def __init__(self):
    super(Identity, self).__init__()

  def forward(self, x):
    return x

In [ ]:
# getting the model
model = torchvision.models.vgg16(pretrained=True)

In [ ]:
# Tuning the model, this code below makes the layers not trainable(trianable=False)
for params in model.parameters():
  params.requires_grad=False

In [ ]:
# changing the avgpool and classifier 
model.avgpool = Identity()
model.classifier = nn.Sequential(
    nn.Linear(512, 100),
    nn.ReLU(),
    nn.Linear(100, 10)
)
model.to(device)

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [ ]:
# loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(params = model.parameters(), lr=learning_rate)

In [ ]:
# training loop
for epoch in range(epochs):
  losses = []
  for index, (data, target) in enumerate(train_loader):

    data = data.to(device)
    target = target.to(device)

    # forward prop
    scores = model(data)
    loss = criterion(scores, target)

    losses.append(loss.item())

    # backward prop
    optimizer.zero_grad()
    loss.backward()

    # gradient step
    optimizer.step()

  print(f"Loss at Epoch {epoch+1}: {((sum(losses)/ len(losses)))}")

Loss at Epoch 1: 1.6074142407397836
Loss at Epoch 2: 1.2190609708124278
Loss at Epoch 3: 1.1484228980784514
Loss at Epoch 4: 1.1130682108353596
Loss at Epoch 5: 1.0906659243058185


### Building Custom Image Datasets

In [ ]:
import pandas as pd
import os
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from skimage import io

In [ ]:
# building a class to load the data 
# the csv file contains - Image name in first column and the class (dog or cat) in the second column

# the following class has method to get one image and corresponding labels
class CatsAndDogs(Dataset):
  def __init__(self, csv_file, root_dir, transform=None):
    self.annotations = pd.read_csv(csv_file)
    self.root_dir = root_dir
    self.transform = transform

  def __len__(self):
    return len(self.annotations)

  def __getitem__(self, index):
    img_path = os.path.join(self.root_sir, self.annotations.iloc[index, 0])
    image = io.imread(img_path)  # image
    y_label = torch.tensor(int(self.annotations.iloc[index, 1]))  # label

    # applying the transforms
    if self.transform:
      image = self.transform(image)

    return (image, y_label)

In [ ]:
# Loading the data throught the class we just made 
csv_file = 'cats_and_dogs.csv'  # name of the csv file
root_dir = os.getcwd()
batch_size = 512

dataset = CatsAndDogs(csv_file, root_dir, transform=torchvision.transforms.ToTensor())

# train and test data:
train_dataset, test_dataset = torch.utils.data.random_split(dataset, [20000, 5000])

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)